name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build_doxygen
      run: |
        apt update
        apt install -y cmake
        cmake -Bbuild -DINSTALL_DEPS=ON .
        # make -j install
    - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        folder: build/doc/html
        config_file: build/Doxyfile
